AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mcsam

  Sample SAM Template for mcsam

Globals:
  Function:
    Timeout: 3

Resources:
  DeploymentPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref ChromiumLayer
      Principal: '*'

  DeploymentPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref PythonDepLayer
      Principal: '*'

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-selenium-layer
      Description: Headless Chromium and Selenium WebDriver
      ContentUri: ./layers/selenium-binaries
      CompatibleRuntimes:
        - nodejs8.10
        - python3.8
        - python2.7
        - go1.x
        - java8
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  PythonDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-layer
      Description: Selenium, Requests, Chromedriver-binary
      ContentUri: ./layers/python-dependencies
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  McsamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mcsam/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Mcsam:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mcsam
            Method: get
      MemorySize: 764
      Timeout: 300
      Layers:
        - !Ref ChromiumLayer
        - !Ref PythonDepLayer
      Environment:
        Variables:
          CLEAR_TMP: "true"
          PATH: /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin:/tmp/bin:/tmp/bin/lib
          DYNAMODB_TABLE: !Ref mindfulrecepies
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonDynamoDBFullAccess

  getmcfunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./getmcfunction
      Handler: exports.handler
      Runtime: nodejs10.x
      MemorySize: 764
      Timeout: 300
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref mindfulrecepies
      Role: 'arn:aws:iam::844633438632:role/LambdaRole'
          
  mindfulrecepies:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mindfulrecepie
      AttributeDefinitions:
      - AttributeName: listingId
        AttributeType: S
      KeySchema:
      - AttributeName: listingId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
        
  sendmindfulrecepies:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.sendmindfulrecepies
      Runtime: nodejs10.x
      CodeUri: ./senddonkeyjobs
      Description: 'this will send a JSON file to csebast for consumption'
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::844633438632:role/LambdaRole'

Outputs:
  McsamApi:
    Description: "API Gateway endpoint URL for Prod stage for mcsam function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mcsam/"
  McsamFunction:
    Description: "mcsam Lambda Function ARN"
    Value: !GetAtt McsamFunction.Arn
  McsamFunctionIamRole:
    Description: "Implicit IAM Role created for mcsam function"
    Value: !GetAtt McsamFunctionRole.Arn
